-- Question 15: Identify the top 5 doctors who generated the most revenue but had the fewest patients.
select `Doctor Name` as Doctor, sum(`Total Bill`) as Revenue,
count(distinct patient_id) as no_of_patients
from doctor
group by Doctor
order by Revenue desc , no_of_patients asc 
limit 5;

-- Question 16: Find the department where the average waiting time has decreased over three consecutive months.
with cte as
(select department_referral, `date`,
round(avg(patient_waittime), 2) as average_wait_time
from hospital
group by department_referral, `date`),

cte2 as 
(select department_referral, `date`, average_wait_time,
lag(average_wait_time, 1) over (partition by department_referral order by `date`) as previous_month_average,
lag(average_wait_time, 2) over (partition by department_referral order by `date`) as previous_2_month_average,
lag(average_wait_time, 3) over (partition by department_referral order by `date`) as previous_3_month_average
from cte)

select department_referral
from cte2
where average_wait_time < previous_month_average
and previous_month_average < previous_2_month_average
and previous_2_month_average < previous_3_month_average
group by department_referral;

-- Question 17: Determine the ratio of male to female patients for each doctor and rank the doctors based on this ratio.
with cte as 
(select d.`Doctor Name` as Doctor_Name,
sum(case when h.patient_gender = "M" then 1 else 0 end) as male_count,
sum(case when h.patient_gender = "F" then 1 else 0 end) as female_count
from hospital h 
inner join doctor as d on h.patient_id = d.patient_id
group by Doctor_Name),

cte2 as 
(select Doctor_Name, male_count, female_count,
round((male_count/female_count),2) as Male_To_Female_ratio
from cte)

select Doctor_Name, male_count, female_count, Male_To_Female_ratio,
dense_rank() over(order by Male_To_Female_ratio desc) as Ranking 
from cte2;

-- Question 18:  Calculate the average satisfaction score of patients for each doctor based on their visits.
select d.`Doctor Name` as Doctor_Name,
round(avg(case when h.patient_sat_score = "" then 5 else h.patient_sat_score end),2) as patient_sat_score
from hospital h 
inner join doctor d 
on h.patient_id = d.patient_id
group by Doctor_Name
order by patient_sat_score desc;

-- Question 19: Find doctors who have treated patients from different races and calculate the diversity of their patient base.
select d.`Doctor Name` as Doctor_Name,
count(distinct h.patient_race) as differnet_race_count
from hospital h 
inner join doctor d
on h.patient_id = d.patient_id
group by Doctor_Name
having count(distinct h.patient_race) > 1
order by differnet_race_count desc;

-- Question 20: Calculate the ratio of total bills generated by male patients to female patients for each department.
select h.department_referral,
sum(case when patient_gender = "M" then d.`Total Bill` end) as Male_total_bill,
sum(case when patient_gender = "F" then d.`Total Bill` end) as Female_total_bill,
round(sum(case when patient_gender = "M" then d.`Total Bill` end) / sum(case when patient_gender = "F" then d.`Total Bill` end),2) as Male_To_Female_Ratio
from hospital h 
inner join doctor d
on h.patient_id = d.patient_id
group by h.department_referral;

-- Question 21: Update the patient satisfaction score for all patients who visited the "General Practice" department and had a waiting time of more than 30 minutes. Increase their satisfaction score by 2 points, but ensure that the satisfaction score does not exceed 10.
update hospital
set patient_sat_score = least(patient_sat_score + 2,10)
where lower(department_referral) = "general practice" and patient_waittime > 30;